class pxe::httpd {
    package {
        'httpd': ensure => installed; 
        'createrepo': ensure => installed;
    }
    
    service {
        'httpd': ensure => running, enable => true;
    }
    
    file { '/etc/httpd/conf.d/pxe.conf':
		ensure => 'present',
		owner => 'root',
		group => 'root',
		mode => 0400,
        content => '
Alias /centos6_x86_64 /var/lib/tftpboot/centos6_x86_64

<Directory /var/lib/tftpboot/centos6_x86_64>
Options Indexes FollowSymLinks
Order Deny,Allow
#Deny from all
Allow from all
</Directory>
',
        require => Package['httpd'],
        notify => Service['httpd'];
    }   
    
    file { '/var/www/html/centos.cfg':
		ensure => 'present',
		owner => 'root',
		group => 'root',
		mode => 0444,
        content => "# Kickstart file automatically generated by anaconda.
#version=DEVEL
install
text
url --url http://10.10.10.5/centos6_x86_64
lang en_US.UTF-8
keyboard us
network --onboot yes --device eth0 --bootproto dhcp --noipv6
rootpw --plaintext student
firewall --disabled
authconfig --enableshadow --passalgo=sha512
timezone --utc Etc/UTC
bootloader --location=mbr --driveorder=sda --append='crashkernel=auto rhgb quiet'
user --name=student --password=student

# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clear all partitions first, this is
# not guaranteed to work

# Clean out the old disk config
zerombr

# Clean out old partitions
clearpart --all --drives=sda

autopart


repo --name pxe-repo --baseurl=http://10.10.10.5/repo/

%packages --nobase
	@core

    @basic-desktop

    gedit
    gcalctool
    vim-X11
    vim
    dejavu-sans-fonts
    dejavu-serif-fonts
    dejavu-sans-mono-fonts
    firefox
    ntp
    openssh-clients

    VirtualBox-4.3
    btsync
    screen
    telnet
    unzip
    lsof
    wget
    sysstat
    man
%end

%post

	# Change to a vt to see progress

	exec < /dev/tty3 > /dev/tty3
	chvt 3

	(
		#######################################################
		# Turn off un-needed services
		#######################################################
		chkconfig sendmail off
		chkconfig smartd off
		chkconfig cupsd off

        chkconfig ntpdate on
        chkconfig ntpd on


		# Cleanup other files we do not need
		yum -y groupremove 'Dialup Networking Support' 'Printing Support' 'Additional Development' 'E-mail server'

		# Default to runlevel 5
		sed -i 's/id:3:initdefault:/id:5:initdefault:/g' /etc/inittab
        
        # Setup cron.sh 
        echo '*/5 * * * * root curl -sSL https://raw.githubusercontent.com/jayjanssen/pxc_training_pxe/master/cron.sh | sh' > /etc/cron.d/pxc_training_cron

	) 2>&1 | /usr/bin/tee /root/ks-post.log

	# switch back to gui
	chvt 7

%end

reboot
",
        require => Package['httpd'];
    }   
    
    
    
    
    
    file { 
    '/var/repo':
        ensure => directory,
    	owner => 'root',
    	group => 'root',
    	mode => 0555;
    '/etc/httpd/conf.d/repo.conf':
		ensure => 'present',
		owner => 'root',
		group => 'root',
		mode => 0400,
        content => 'Alias /repo /var/repo

<Directory /var/repo>
Options Indexes FollowSymLinks
Order Deny,Allow
#Deny from all
Allow from all
</Directory>
',
        require => File['/var/repo'],
        notify => Service['httpd'];
    }   
    
    exec { 
    'cp_rpms':
        cwd => '/var/repo',
        command => 'cp /vagrant/repo/* /var/repo',
        path => ['/usr/bin', '/bin'],
        unless => 'ls /var/repo/*.rpm';
     'create_repo':
         cwd => '/var/repo',
         command => 'createrepo .',
         path => ['/usr/bin', '/bin'],
         creates => '/var/repo/repodata',
         require => [Exec['cp_rpms'],Package['createrepo']];
    }
}